<?php
if(function_exists("register_field_group"))
{
    register_field_group(array (
        'id' => 'acf_gallery-item',
        'title' => 'Gallery-item',
        'fields' => array (
            array (
                'key' => 'field_576a03e23fc69',
                'label' => 'Gallery Thumbnail Size',
                'name' => 'gallery_thumbnail_size',
                'type' => 'select',
                'instructions' => 'If using masonry layout - choose the size here:',
                'required' => 1,
                'choices' => array (
                    'small' => 'Small',
                    'wide' => 'Wide',
                    'large' => 'Large',
                ),
                'default_value' => 'small',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_576a05a53fc6b',
                'label' => 'Gallery Wide Image',
                'name' => 'gallery_wide_image',
                'type' => 'image',
                'instructions' => 'Add Gallery Thumbnail Preview Image: 1300 x 650',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_576a03e23fc69',
                            'operator' => '==',
                            'value' => 'wide',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'save_format' => 'object',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_576a04bc3fc6a',
                'label' => 'Gallery Square Image',
                'name' => 'gallery_square_image',
                'type' => 'image',
                'instructions' => 'Add Gallery Thumbnail Preview Image: 1100x1100',
                'required' => 1,
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_576a03e23fc69',
                            'operator' => '!=',
                            'value' => 'wide',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'save_format' => 'object',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'gallery',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'acf_after_title',
            'layout' => 'no_box',
            'hide_on_screen' => array (
                0 => 'discussion',
                1 => 'comments',
                2 => 'author',
                3 => 'format',
                4 => 'send-trackbacks',
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_gallery-thumb',
        'title' => 'Gallery-thumb',
        'fields' => array (
            array (
                'key' => 'field_5769e1482c05a',
                'label' => 'Gallery Type',
                'name' => 'gallery_type',
                'type' => 'select',
                'instructions' => 'Select the type of grid you want displayed',
                'required' => 1,
                'choices' => array (
                    'masonry' => 'Masonry',
                    '3col' => '3 Column',
                    '4col' => '4 Column',
                ),
                'default_value' => 'Masonry',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_5769e1fa2c05b',
                'label' => 'Show Filter',
                'name' => 'show_filter',
                'type' => 'true_false',
                'instructions' => 'Enable to display filtering categories for the gallery page',
                'message' => '',
                'default_value' => 1,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-gallery.php',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'acf_after_title',
            'layout' => 'no_box',
            'hide_on_screen' => array (
                0 => 'custom_fields',
                1 => 'discussion',
                2 => 'comments',
                3 => 'author',
                4 => 'format',
                5 => 'tags',
                6 => 'send-trackbacks',
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_team-section',
        'title' => 'Team Section',
        'fields' => array (
            array (
                'key' => 'field_5765b8f0f5c1b',
                'label' => 'Full Name',
                'name' => 'full_name',
                'type' => 'text',
                'required' => 1,
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5765b922f5c1c',
                'label' => 'Profile Image',
                'name' => 'profile_image',
                'type' => 'image',
                'instructions' => 'Recommended Image Size: 350 x 350 px',
                'required' => 1,
                'save_format' => 'object',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_5765b94cf5c1d',
                'label' => 'Bio',
                'name' => 'bio',
                'type' => 'textarea',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'br',
            ),
            array (
                'key' => 'field_5765b9d4cc3a9',
                'label' => 'Job Title',
                'name' => 'job_title',
                'type' => 'text',
                'required' => 1,
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'team',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array (
                0 => 'the_content',
                1 => 'excerpt',
                2 => 'custom_fields',
                3 => 'discussion',
                4 => 'comments',
                5 => 'revisions',
                6 => 'slug',
                7 => 'author',
                8 => 'format',
                9 => 'featured_image',
                10 => 'categories',
                11 => 'tags',
                12 => 'send-trackbacks',
            ),
        ),
        'menu_order' => 0,
    ));
}
